title: COVID-19 evolution in France 
author: Serge Dudnic
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The site about COVID-19 evolution in France, 
  graphs and API's used to show the new virus
  propagation, cases, recoveries, deaths etc.

theme: jekyll-theme-cayman

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
